USE [DBVendas]
GO

/****** Object:  Table [dbo].[TB_ProdutoPLS]    Script Date: 24/11/2021 01:07:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_ProdutoPLS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[DescricaoProd] [varchar](100) NULL,
	[ID_Categoria] [bigint] NOT NULL,
 CONSTRAINT [PK_TB_ProdutoPLS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TB_ProdutoPLS]  WITH CHECK ADD  CONSTRAINT [FK_TB_CategoriaPLS_TB_ProdutoPLS] FOREIGN KEY([ID_Categoria])
REFERENCES [dbo].[TB_CategoriaPLS] ([ID])
GO

ALTER TABLE [dbo].[TB_ProdutoPLS] CHECK CONSTRAINT [FK_TB_CategoriaPLS_TB_ProdutoPLS]
GO


