USE [DBVendas]
GO

/****** Object:  Table [dbo].[TB_CategoriaPLS]    Script Date: 23/11/2021 22:48:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_CategoriaPLS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[Descricao] [varchar](60) NULL,
 CONSTRAINT [PK_TB_CategoriaPLS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


